[package]
name = "svgtopng"
version = "0.1.0"
authors = ["chikamim"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"

[dependencies]
resvg = "0.3.0"
libc = "0.2.2"

[features]
cairo-backend = ["resvg/cairo-backend"]

[lib]
crate-type = ["cdylib"]
